### ISSUE TITLE
Implement Skip SSL Validation by Default Per Backend

### ISSUE THREAD

**Issue by thomasmmitchell** [starkandwayne/shield#174]
In many cases, people cannot get signed certs for their SHIELD deployment. These lowly plebeians must resort to typing the `-k` option for every command they want to execute. That's sort of lame.

Turns out, though, that if you're using `-k` for a backend for one command, you probably want to use `-k` for every command given to that backend, at least until the powers that be hand you a trusted certificate. Therefore, there should probably a property for configured backends called something like `SSL Validation`.

For backward compatibility reasons, not having this value at all in a config should default it to true. If the value is false, then treat all input commands targeting that backend as if they were specified with `-k`.

**Comment by jhunt** [comment]
You can set `SHIELD_SKIP_SSL_VERIFY=` in your environment, but you're right, we ought to fix this in the configuration file.

**Comment by thomasmmitchell** [comment]
@geofffranks I think you looked into this way back and said something about the configuration file didn't gel with this idea? Do you remember what was up with that?

**Comment by geofffranks** [comment]
Mostly that we'd have to do something similar to the saferc format, where there's a top-level key for SHIELD servers that we want to skip verification for, mapping to the backends in the config.. something like:

```
backend: test
backends:
  http://localhost:8181: Basic YmxhcmcK
  https://10.244.2.2.xip.io: Basic YmxhcmcK
aliases:
  bosh-lite: https://10.244.2.2.xip.io
  localdev: http://localhost:8181
  shield: http://localhost:8181
skip_verify:
  https://localhost:8181: true
```

When i use the `shield` or `localdev` shield backends, it skips verification, but `bosh-lite` would not.
